// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// distance_calc
double distance_calc(int x1, int y1, int x2, int y2);
RcppExport SEXP MixFishSim_distance_calc(SEXP x1SEXP, SEXP y1SEXP, SEXP x2SEXP, SEXP y2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< int >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< int >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< int >::type y2(y2SEXP);
    __result = Rcpp::wrap(distance_calc(x1, y1, x2, y2));
    return __result;
END_RCPP
}
// move_prob
NumericMatrix move_prob(NumericVector start, double lambda, NumericMatrix hab);
RcppExport SEXP MixFishSim_move_prob(SEXP startSEXP, SEXP lambdaSEXP, SEXP habSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type start(startSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type hab(habSEXP);
    __result = Rcpp::wrap(move_prob(start, lambda, hab));
    return __result;
END_RCPP
}
// move_prob_Lst
List move_prob_Lst(double lambda, NumericMatrix hab);
RcppExport SEXP MixFishSim_move_prob_Lst(SEXP lambdaSEXP, SEXP habSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type hab(habSEXP);
    __result = Rcpp::wrap(move_prob_Lst(lambda, hab));
    return __result;
END_RCPP
}
// move_population
List move_population(List moveProp, NumericMatrix StartPop);
RcppExport SEXP MixFishSim_move_population(SEXP movePropSEXP, SEXP StartPopSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type moveProp(movePropSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type StartPop(StartPopSEXP);
    __result = Rcpp::wrap(move_population(moveProp, StartPop));
    return __result;
END_RCPP
}
